FROM ocaml/opam2 as build
WORKDIR lgtm
RUN sudo apt-get update -y && sudo apt-get install -y \
	pkg-config \
	libgmp-dev \
	m4
RUN opam install -y dune \
	tls \
	cohttp \
	cohttp-lwt-unix \
	yojson \
	atdgen
ADD . .
RUN sudo chown -R opam:nogroup .
RUN bin/build

FROM debian:buster-slim
RUN apt-get update -y && apt-get install -y \
        netbase -y
COPY --from=build /home/opam/opam-repository/lgtm/_build/default/src/main.exe bin/lgtm