FROM ocaml/opam2 as build
WORKDIR lgtm
RUN sudo apt-get update -y && sudo apt-get install -y \
	pkg-config \
	libgmp-dev \
	m4
RUN opam install -y dune \
	tls \
	cohttp \
	cohttp-lwt-unix \
	yojson \
	atdgen
ADD . .
RUN sudo chown -R opam:nogroup .
RUN ./bin/build
RUN mkdir release
RUN mv _build/default/src/main.exe release/lgtm
